# 有个细节还是说下：方便新人了解，docker-compose up会创建的默认的网络，网络的名称为 ”当前compose文件所在文件夹名称_default“，例如此配置文件在data目录下，所以默认网络为 data_default
# 设置COMPOSE_PROJECT_NAME环境变量可以定制默认网络名称
# 在同一个compose配置文件中启动的所有容器默认会加入同一个网络，so,容器间互相访问可以直接通过容器container_name访问，无需额外的配置
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "26306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_DATABASE: xh
      #MYSQL_USER: xh
      #MYSQL_PASSWORD: xh123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      #- ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis
    container_name: redis
    ports:
      - "26379:6379"
    volumes:
      - ./redis/data:/data
      #- ./redis/redis.conf:/etc/redis/redis.conf
    restart: unless-stopped
    command: redis-server --appendonly yes

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "29100:9000"
      - "29101:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    restart: always

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    # 用root用户启动，因为jenkins需要调用宿主机的docker,docker-compose，会有权限问题，怕麻烦直接root省事，但要注意网络安全
    user: root
    ports:
      - "29180:8080"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime
      # 映射宿主机docker，这样再容器内部执行docker就等于在宿主机执行
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker
      # 映射宿主机docker-compose，这样再容器内部执行docker-compose就等于在宿主机执行
      #- /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      #- /usr/bin/docker-compose:/usr/bin/docker-compose
    environment:
      JAVA_OPTS: "-Xmx256m -Xms256m"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
    restart: always
    privileged: true

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    ports:
      - "28088:8080"
    volumes:
      - ./xxl-job:/data/applogs
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=${MYSQL_PASSWORD}"
    depends_on:
      - mysql
    restart: always

  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: nacos
    environment:
      MODE: "standalone"
      SPRING_DATASOURCE_PLATFORM: "mysql"
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: "3306"
      MYSQL_SERVICE_DB_NAME: "nacos_config"
      MYSQL_SERVICE_USER: "root"
      MYSQL_SERVICE_PASSWORD: ${MYSQL_PASSWORD}
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_IDENTITY_KEY: "xh"
      NACOS_AUTH_IDENTITY_VALUE: "xh666"
      NACOS_AUTH_TOKEN: "dlfkgjer78234uskl23ioufsjlk34r9028rf0wu24078woekrjelwriufio"
      JVM_XMS: "256m"
      JVM_XMX: "256m"
      JVM_XMN: "64m"
    volumes:
      - ./nacos/logs:/home/nacos/logs
    ports:
      - "28848:8848"
      - "29848:9848"
    depends_on:
      - mysql
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "22180:80"
    restart: always
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/cer:/etc/nginx/cer:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./xh/frontend:/usr/share/nginx/html

  system:
    image: hwjdk:21-zh
    container_name: system
    ports:
      - "28280:8080"
    restart: always
    volumes:
      - ./xh/backend:/jars
    command: ["-Xmx1024m", "-jar", "/jars/system-service-0.0.1-SNAPSHOT.jar"]

  generator:
    image: hwjdk:21-zh
    container_name: generator
    ports:
      - "28380:8080"
    restart: always
    volumes:
      - ./xh/backend:/jars
    command: ["-Xmx1024m", "-jar", "/jars/generator-service-0.0.1-SNAPSHOT.jar"]
